name: Upload Files to Private Repo

on:
  workflow_dispatch:  # This allows manual triggering of the workflow
  repository_dispatch:  # This allows triggering from an external source
    types: [upload-file]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Upload File to Private Repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        FILE_PATH=${{ github.event.client_payload.file_path }}
        FILE_CONTENT=${{ github.event.client_payload.file_content }}
        REPO=YOUR_USERNAME/YOUR_PRIVATE_REPO
        COMMIT_MSG="Add ${FILE_PATH}"
        echo "$FILE_CONTENT" | base64 -d > $FILE_PATH
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add $FILE_PATH
        git commit -m "$COMMIT_MSG"
        git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/$REPO HEAD:main
